### ISSUE TITLE
Integration request: Quirky Aros AC

### ISSUE THREAD

**Issue by Weldon26** [KraigM/homebridge-wink#10]
The Wink plug-in is amazing! I couldn't have imagined so many of my devices could be working with HomeKit so quickly.

Are there any plans for Aros AC's to be included at some point?

Or, considering these units are advertised as wifi and can be used without a Wink hub, is it possible that another existing plug-in that I've overlooked may be compatible with them already?

Thanks

**Comment by pdlove** [comment]
If you'll agree to test it, I'll write the "Air Conditioner" interface at the same time I do the "Thermostat" interface.

**Comment by Weldon26** [comment]
I’ll be happy to test it! I’ve added you as a user to one of my AC’s and two of my door sensors: one GoControl, the other Quirky.

And in case you were interested in poking around further, I added you to a motion detector and… an egg minder. Don’t tease. Yes. I bought the egg minder for $10 on Amazon. I figure not many people will admit to buying one so if you ever were curious about one, you’d have a hard time finding one to connect to. But it’s there if you want. 

Thanks!

**Comment by pdlove** [comment]
Wow. I've got a ton of devices now between everyone willing to help donate their device access for development.
I'm not sure what to do with the Egg Minder (Or Portfolio) in home bridge but will look when I'm done with the other items.
What do you think of the Egg Minder? I've considered picking a couple up for the $10 rate. Is it a good sturdy container for eggs?

**Comment by pdlove** [comment]
I have a dilemma on the Air Conditioner. The way HomeKit handles the Thermostat, it doesn't have a fan-only control. As I've implemented this, the Air Conditioner shows up as two different types. One is a fan which you can turn on or off and control the speed... The other is a thermostat. 
The issue that I'm having is that when you turn the fan on, it will automatically switch the unit to fan only mode.
I'm considering ignoring the fan side altogether which would simply make the modes Cool, Auto and Off.
Any thoughts?

**Comment by Weldon26** [comment]
Well -- I'd really like to have fan control. And I could train myself to remember setting the ac is a two step process.... choose the fan speed, then choose the mode.

I think that many people, however, unless they configure homebridge themselves, wouldn't recognize the two steps on their own and might consider the implementation to be, at best, non-intuitive, and at worst, unreliable, unpredictable, or buggy.

So, as much as I'd like full control over the units myself, I have to agree with you. Maybe it's best to ignore the fan side. Across the board, people will be happier with intuitive limited functionality than they would be with full functionality they consider (incorrectly) to be broken or "quirky."

If you're having doubts, maybe you could provide two implementations and allow users to decide on their own which best suits their needs when defining their AC's in the config.

Hell -- if you just give us on/off, anybody affected will be thrilled just to be able to do more than we could this morning. :)

Thanks again for working on this!

**Comment by Weldon26** [comment]
oh - and, yes... the egg minder is a sturdy container. it;s got a heavy base and a solid lid. i DID run the batteries down once when an extremely large extra-large egg kept the lid from seating solidly. And it coulda gotten messy had i NOTICED the lid wasn't seated properly and just pushed harder on it. That's the only issue I've had with it and, seriously... that was ONE BIG EGG. I don't expect to run into that issue again.

**Comment by pdlove** [comment]
I have my own hens and like the idea of moving up from using the old, falling apart foam containers. Thanks for the feedback.
I'll publish it without the separate fan control and we'll add it with an option to enable it later.
In "auto Eco" mode, does the unit adjust the fan speed by itself?

**Comment by Weldon26** [comment]
yeah - if you have your own hens, your eggs deserve something sturdy. I'd say get one. i think you'll like it.

i'm fairly certain that the fan speed remains constant in auto eco mode -- whichever setting a user has chosen -- and the fan and compressor kick off when the desired temperature is reached. they kick on again when the room begins to get warmer.

i'm going to try testing that right now to make sure i'm not giving you bad info. it's *possible* (but unlikely) that the fan *does* adjust itself and i've just learned to not hear it. or that the fan kicking into high gear already made me deaf and *that's* why i don't hear it. these are far from whisper-quiet. i'll post back within the next 20 minutes if i see (or hear) any indication description that my description of auto/eco above is inaccurate.

**Comment by Weldon26** [comment]
I think the manual's description is maybe a bit better than my own:

ECO MODE
This mode optimizes the cooling power of your air conditioner, thereby saving you energy. Once the set point temperature has been reached, the fan will cycle o  to save energy. The fan will cycle back on periodically to ensure all cooling capacity in the system is used. This mode is the default mode for the unit. Each time the unit is powered on, it will restart in Eco mode ON. The first time the unit is turned on, the settings will be 70° and Low fan. You can adjust the fan speed and temperature to your personal comfort.

Eco ON helps minimize electricity use. It is normal for the fan to cycle off and then back on in this mode. This on/off cycle can repeat multiple times. Because the fan will cycle off, you may notice a variation in room temperature and humidity.

Eco OFF When this mode is not engaged, the fan will run continuously, and in Cool mode the compressor will cycle on and off to maintain room temperature.

**Comment by pdlove** [comment]
Full support, including for the fan speed, is in PR #11.

**Comment by KraigM** [comment]
Released under 1.0.0/1.0.1
