### ISSUE TITLE
Color control of Lights

### ISSUE THREAD

**Issue by msroest** [KraigM/homebridge-wink#13]
I have a EcoSmart (home depot brand) multi color LED. It seems to work fine for on/off and dimming through the homebridge, but they aren't advertising color control to HomeKit.

Not sure if there is any planned work to support this I'm going to try to work through it on my own but any tips about where to look/start would be appreciated.

**Comment by pdlove** [comment]
I've submitted changes that allow Hue and Saturation control. On Apple's side, that's how they allow color selection. I'm not sure if EcoSmart is controlled that way or if I need to add a conversion from the Hue/Saturation to RGB. I'll put together instructions on install my test version so that you can try it out if you would like. Alternatively, if you share one of your lights with me on wink (pdlovelace@gmail.com) then I can let you know if it will work.

**Comment by msroest** [comment]
I've shared the light with you, and asked my Wife to turn the dumb switch on to get it power (waiting for a z-wave 3-way switch set to be able to control it remotely).

If you try it and the light isn't on just email me mike@roe.st and I'll get it switched on.

**Comment by pdlove** [comment]
Looks like I'm not passing the Hue to it properly. I'll work with it tonight and get it going in my test version. Thanks for the share of the light!

**Comment by msroest** [comment]
Awesome thanks!

**Comment by pdlove** [comment]
You can unsure the bulb. It is working beautifully in my test version now.

**Comment by msroest** [comment]
Ok sure.  Thanks! for working on that.

If you're looking for other things to implement.  I also have the GoControl door/window sensors, Motion detector and Siren more then willing to share them as well.

**Comment by pdlove** [comment]
The Siren is the only thing that isn't in the code being evaluated right now.
I've got a Siren example, but HomeKit doesn't have the services to tie it to.

**Comment by msroest** [comment]
Could it be treated by HomeKit like 2 binary switches? One for the siren
and one for the light.

**Comment by pdlove** [comment]
That would work. A switch and a light. I'll add this to my run in the morning. I will not be testing it but am confident it will work.

**Comment by pdlove** [comment]
This is all good in PR #11

**Comment by KraigM** [comment]
Released under 1.0.0/1.0.1
