### ISSUE TITLE
Allow for security devices like doors and garage doors to be open with Siri without unlocking phone

### ISSUE THREAD

**Issue by niagaraguy** [KraigM/homebridge-wink#15]
Allow for security devices like doors and garage doors to be open with Siri without unlocking phone
Make door  think it is a light or plug?  Or trigger of another device ? 
What about a switch in the configuration  that could allow the garage to be a true garage for those that want it that way and or to also allow for it to act more like a power outlet on (open) or off (shut)

The way I would implement this would be to have a configuration option “groups to treat as switches”. That would allow people not concerned with security to add locks, garage door openers and whatever else.

**Comment by KraigM** [comment]
If you do this then many Siri commands will mess up and try to change it. Apple does this so that if someone steals your phone then they won't be able to access your home with it

**Comment by niagaraguy** [comment]
Can you expand on this ? I find it  interesting that it would be more of a security issue of somebody stealing my phone than breaking into my car with the garage remote in it or a home link Button on the rear view  mirror. To get to my phone you have to go through me. 😀

**Comment by jclarke0000** [comment]
If you're not concerned with security, you can just turn off the lock code on your phone, and you'll have what you want. 

Trying to circumvent built-in security is a good way to get Apple's attention and have them lock out HomeBridge from their system. Bad for all of us.

**Comment by KraigM** [comment]
@jclarke0000 perfectly put

**Comment by niagaraguy** [comment]
Sent request to Apple to allow after acknowledging security risk. Will see what happens. 

Thanks
