### ISSUE TITLE
Pivot Power Genius Outlet Support

### ISSUE THREAD

**Issue by techyowl** [KraigM/homebridge-wink#2]
This is a feature request for adding on off home bridge integration with various Wink compatible smart outlets for example the Pivot Power Genius could be one or the Outlink wall reciprocal as another.

**Comment by pdlove** [comment]
This is in PR #11.
Interestingly enough, the plugs on the Pivot Power are Outlets, but the Outlink is showing as a Binary Switch. I just thought that was a bit odd.

**Comment by KraigM** [comment]
Released under 1.0.0/1.0.1

**Comment by rbharris1** [comment]
I installed 1.0.3 and...viola...homebridge sees my pivot power geniuse (ppg) outlets! Thanks for this update! 

The ppg devices also appear in the Insteon+ app, but they don't have any controls. When I click on them they just show the name of the device and the placeholders for mfr and serial no.  When I try to operate by Siri, response is "Sorry, I can't do that."

Any guidance you could provide would be appreciated.
