### ISSUE TITLE
WARN deprecated

### ISSUE THREAD

**Issue by benw525** [KraigM/homebridge-wink#38]
I am trying to install the plugin and I get this returned:

npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/lib

Both graceful and minimatch are higher than the versions stated as the minimum versions. 

I am on a raspberry pi 2 running raspbien.

**Comment by benw525** [comment]
It is actually a Pi3

**Comment by benw525** [comment]
I guess you can close this. I downgraded to node v5 and installed homebridge again. Everything seems to work now.

**Comment by bradleyrawleigh** [comment]
I'm having this same issue, got a new wink hub today, please advise? somewhat new to this, been using homebridge for my wemo devices for about 2 months now without an issue. thanks

**Comment by benw525** [comment]
I wish I could remember how to do it. But you need to downgrade your version of Node.js to node v5. Google around, there are instructions somewhere! Once it's node v5 it should work no problem :)

**Comment by bradleyrawleigh** [comment]
Oh, I've royally screwed it up now. tried downgrading and reinstalling few ways i found online, now when it isn't working at all......



homebridge
/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by benw525** [comment]
Have you tried uninstalling npm and all the npm modules and the installing them again?

**Comment by bradleyrawleigh** [comment]
whats the basic steps to do that? i will try those steps if you can assist me with them please? bought multiple wink devices and a hub and still haven't been able to correct my homebridge to work with all my new goodies.....thanks again

**Comment by benw525** [comment]
Remove node then run:

curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash

**Comment by bradleyrawleigh** [comment]
My newest attempt......and logs of the failures

Bradleys-iMac:~ bradleyrawleigh$ sudo npm cache clean -f
Password:
npm WARN using --force I sure hope you know what you are doing.
Bradleys-iMac:~ bradleyrawleigh$ sudo npm install -g n
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
n@2.1.2 /usr/local/lib/node_modules/n
Bradleys-iMac:~ bradleyrawleigh$ sudo n lts

     install : node-v4.4.7
       mkdir : /usr/local/n/versions/node/4.4.7
       fetch : https://nodejs.org/dist/v4.4.7/node-v4.4.7-darwin-x64.tar.gz
######################################################################## 100.0%
   installed : v4.4.7

Bradleys-iMac:~ bradleyrawleigh$ sudo npm install -g homebridge
Password:
-
> curve25519@1.1.0 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/curve25519
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/bradleyrawleigh/.node-gyp/4.4.7"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/curve25519/.node-gyp"
  CXX(target) Release/obj.target/curve/node_curve.o
  SOLINK_MODULE(target) Release/curve.node

> ed25519@0.0.3 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/ed25519
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/bradleyrawleigh/.node-gyp/4.4.7"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/ed25519/.node-gyp"
  CC(target) Release/obj.target/ed25519/src/ed25519/keypair.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sign.o
  CC(target) Release/obj.target/ed25519/src/ed25519/open.o
  CC(target) Release/obj.target/ed25519/src/ed25519/crypto_verify_32.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_double_scalarmult.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_scalarmult_base.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_precomp_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_cached.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_madd.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_msub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p3.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_1.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_cmov.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_copy.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_neg.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_mul.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_invert.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnegative.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnonzero.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_pow22523.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_reduce.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_muladd.o
  CXX(target) Release/obj.target/ed25519/src/ed25519.o
  SOLINK_MODULE(target) Release/ed25519.node

> mdns@2.3.3 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/bradleyrawleigh/.node-gyp/4.4.7"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/.node-gyp"
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_update_record.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
  SOLINK_MODULE(target) Release/dns_sd_bindings.node

> bignum@0.12.5 install /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum
> node-pre-gyp install --fallback-to-build

[bignum] Success: "/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/srp/node_modules/bignum/binding/bignum.node" is installed via remote
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge
homebridge@0.3.4 /usr/local/lib/node_modules/homebridge
├── semver@5.0.3
├── node-persist@0.0.8 (q@1.1.2, mkdirp@0.3.5)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.1)
├── commander@2.8.1 (graceful-readlink@1.0.1)
└── hap-nodejs@0.3.2 (debug@2.2.0, curve25519@1.1.0, ed25519@0.0.3, mdns@2.3.3, srp@0.2.1)
Bradleys-iMac:~ bradleyrawleigh$ sudo npm install -g homebridge-wink
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
homebridge-wink@1.1.1 /usr/local/lib/node_modules/homebridge-wink
└── wink-js@0.1.1 (async@1.5.2, debug@2.2.0, 

> config-file@0.1.8)

> Not sure where to go from here honestly......getting further in unfamiliar territory now.

Running HomeBridge from node.js on my iMac (side note)


thanks for any further advice again!

**Comment by benw525** [comment]
I assume you've tried just redoing the entire thing?  

Have you tried installing with --unsafe-perm

I'll be honest, I am not sure about running it on Mac OS....I run it off a Debian RPi3

**Comment by bradleyrawleigh** [comment]
should i repost this issue in another area maybe? sorry I'm very new to GitHub, and how to best use its features honestly. thanks

**Comment by benw525** [comment]
I think you should start a new topic
