### ISSUE TITLE
Homebridge and Wink not communicating correctly using iOS10

### ISSUE THREAD

**Issue by sstack124** [KraigM/homebridge-wink#57]
I just setup homebridge for the first time. I am able to get homebridge to communicate with wink but when I use homekit, it says "Sorry, I wasn't able to do that". I see the command in the terminal window but nothing happens. Any thoughts?

[Wink] Changing target property 'powered' of the light_bulbs called Closet to false

**Comment by bradleyrawleigh** [comment]
I have had the same issue for months. Since I started using homebridge. So if you find any resolutions it would be fantastic. I have posted before but gotten no responses. I only have 1 devices connected to wink hub. It's a GE in wall light switch (z-wave)

**Comment by Sturgeon637** [comment]
I don't think it is an iOS10 issue. I think it is an API credentials issues. The current WINK plugin needs version 1 API credentials.  Wink is currently only providing version 2 API credentials. Try using the Android version 1 credentials (google them).

**Comment by lokki911** [comment]
that doesn't work

**Comment by sstack124** [comment]
Thanks Sturgeon637. That worked for me.
