### ISSUE TITLE
Status of Door / Window Sensor

### ISSUE THREAD

**Issue by earlthesquirrel** [KraigM/homebridge-wink#6]
Request to integrate the data updates from Wink Tripper Sensors.
To allow monitoring of open doors / windows.

**Comment by KraigM** [comment]
@pdlove ETA? Can you push what you have done so far to a branch (even if it is broken) so others can pick up where you left off and help?

**Comment by Weldon26** [comment]
I'd like to see door/window sensors, too.

**Comment by pdlove** [comment]
I can probably do the door/window sensors, but I have no examples of these here. Would you mind sharing one of your sensors with my wink account? If you don't mind, I can give you my info and we could even make the AC plugin more seamless that way too in order to reduce the likelihood of any errors on my part.

**Comment by techyowl** [comment]
I can assist with that send me your email attached to your wink account. I have pivot power geniuses, wink outline in wall outlets, the wink relay etc. as long as you give me a heads up that you'll be testing on off functionality for an hour or two lol. I also have door and window sensors. I can hook up a spotter gen 1  multi sensor, let me know.

**Comment by pdlove** [comment]
My email for the wink account is pdlovelace@gmail.com
If you don't mind sending me an email, i will definitely let you know when
I'm ready to test changing any settings. Everything is pretty well
documented so that I can probably get it right just by the read only parts.

**Comment by techyowl** [comment]
@pdlove ok I gave you access to a few various different devices to mess around with. as for the wink relay it doesn't allow me to add a user to it anywhere in the app. not in the lights and outlets section not in the wink relay section and not in the sensors section so not much I can do about that.

**Comment by pdlove** [comment]
@techyowl That has helped a lot. I'm adding a bit of code to the startup portion of the Wink plugin to report device types that it doesn't know how to handle and doesn't know to ignore. We'll use that to find out further information on how the wink relay items represent from the API. I'm hopeful it shows as the 
sensor_pod and binary_switch types

**Comment by pdlove** [comment]
Full support is in PR #11.

**Comment by KraigM** [comment]
Released under 1.0.0/1.0.1
