### ISSUE TITLE
Request to support GE Link Bulbs

### ISSUE THREAD

**Issue by earlthesquirrel** [KraigM/homebridge-wink#7]
This request is to provide support GE Link Bulbs (on/off and light dimming)
GE Link Bulbs are a very common Wink accessory as they were packaged with hubs when they initially came out.

**Comment by KraigM** [comment]
There should be light bulb support already.  I can't test it as I do not have any hooked up anymore.  

I had Philips Hue hooked up to wink and they worked, but the color was off and it messed with my OCD :smile:.  I use the door lock and it _mostly_ works.

**Comment by pdlove** [comment]
I can confirm this works with the GE Link Bulbs as is through the Wink hub.

**Comment by earlthesquirrel** [comment]
After some "twiddling", I now can see them thru homebridge.  Thanks!
