### ISSUE TITLE
Wink Connection Details

### ISSUE THREAD

**Issue by akarmakar** [KraigM/homebridge-wink#82]
i am trying to get wink client_id for that . They use  website for this https://developer.wink.com/login
 Listed below are required info . Any one  know what will be Website & REDIRECT URIS?
Name of Application : homebridge-wink
Website : ?
REDIRECT URIS: ?

**Comment by AppleTechy** [comment]
For website just use the github page for the Wink plugin. And the redirect URL I don't believe is required so you can just skip that

**Comment by akarmakar** [comment]
Thanks for the reply.
Redirect URIs* is required  this is the tool tip on that "Where the client will be redirected upon successful authentication
"

**Comment by AppleTechy** [comment]
Maybe just put N/A or right not applicable. Or if it forces an actual URL. Just write some like: "https://local host: [Homebridge port]"

**Comment by akarmakar** [comment]
@AppleTechy  thanks. i used the same git url and got the client_id & secret . Still  cant make wink 2 work 
 keep getting this error Process: 2807 ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)

**Comment by akarmakar** [comment]
i had to switch over to wink 2 api . it worked for me
